### ISSUE TITLE
Chapters Not found

### ISSUE THREAD

**Issue by kraanzu** [arimatakao/mdx#2]
This example command does not work:

> mdx dl -c 12-34 mangadex.org/title/a3f91d0b-02f5-4a3d-a2d0-f0bde7152370

I get this error

```
 SUCCESS  Fetched manga info
 SUCCESS  Fetched chapters info
 ERROR   Chapters 12-34 not found, try another range, language, translation group etc.
 ```
 
 Edit: Got the same issue with other manga

**Comment by arimatakao** [comment]
I will try to fix it. This problem also appeared in other versions of the program

**Comment by arimatakao** [comment]
Looks like the problem was on the MangaDex side. I tested with some manga and everything works fine.

https://github.com/arimatakao/mdx?tab=readme-ov-file#getting-error-chapters-x-y-not-found-try-another-range-language-translation-group-etc
